---
- name: raspberrypi
  hosts: rpi
  roles:
    - role: docker
      tags: ["docker"]
    - role: pihole
      tags: ["dns"]
    - role: bind9
      tags: ["dns"]
    - role: node-exporter
      tags: ["node-exporter"]
