---
- name: raspberrypi
  hosts: rpi
  vars:
    node_exporter_arch: armv6
  roles:
    - role: docker
      tags: ["docker"]
    - role: pihole
      tags: ["dns"]
    - role: bind9
      tags: ["dns"]
    - role: coredns
      tags: ["coredns", "dns"]
    - role: node-exporter
      tags: ["node-exporter"]
- name: ingress
  hosts: ingress
  roles:
    - role: docker
    - role: traefik
    - role: node-exporter
  vars:
    node_exporter_arch: amd64
- name: monitoring
  hosts: monitoring
  roles:
    #- role: docker
    #- role: node-exporter
    #- role: prometheus
    - role: grafana
  vars:
    node_exporter_arch: amd64
