---
- name: orangepi
  hosts: opi
  vars:
    node_exporter_arch: armv7
  roles:
    - role: node-exporter
- name: raspberrypi
  hosts: rpi
  vars:
    node_exporter_arch: armv6
  roles:
    - role: docker
      tags: ["docker"]
    - role: pihole
      tags: ["dns"]
    #- role: bind9
    #  tags: ["dns"]
    - role: coredns
      tags: ["coredns", "dns"]
    - role: node-exporter
      tags: ["node-exporter"]
- name: ingress
  hosts: ingress
  roles:
    - role: docker
    - role: traefik
      tags: ["ingress"]
    - role: node-exporter
      tags: ["ingress"]
  vars:
    node_exporter_arch: amd64
- name: monitoring
  hosts: monitoring
  roles:
    - role: docker
    - role: node-exporter
      tags: ["monitoring"]
    - role: prometheus
      tags: ["monitoring"]
    - role: grafana
      tags: ["monitoring"]
  vars:
    node_exporter_arch: amd64
- name: consul
  hosts: consul
  roles:
    - role: consul
      tags: ["consul"]
- name: hass
  hosts: hass
  roles:
    - role: hass
      tags: ["hass"]
#- name: vault
#  hosts: vault
#  roles:
#    - role: vault
#      tags: ["vault"]
