---
- name: orangepi
  hosts: opi
  vars:
    node_exporter_arch: armv7
  roles:
    - role: node-exporter
- name: raspberrypi
  hosts: rpi
  vars:
    node_exporter_arch: armv6
  roles:
    - role: docker
      tags: ["docker"]
    - role: pihole
      tags: ["dns"]
    #- role: bind9
    #  tags: ["dns"]
    - role: coredns
      tags: ["coredns", "dns"]
    - role: node-exporter
      tags: ["node-exporter"]
- name: consul
  hosts: consul
  roles:
    - role: consul
      tags: ["consul"]
