---
- name: CoreDNS | Make sure coredns user exists
  user:
    name: coredns
    group: users
    groups:
      - sudo
    state: present
- name: CoreDNS | Make sure the coredns config folders exist
  file:
    path: "{{ item }}"
    state: directory
    owner: coredns
    group: users
  with_items:
    - /etc/coredns
    - /etc/coredns/zones
- name: CoreDNS | Install
  copy:
    src: "coredns_1.1.1_armv6/coredns"
    dest: /usr/local/bin/coredns
    mode: 0755
- name: CoreDNS | Set capabilities
  capabilities:
    path: /usr/local/bin/coredns
    capability: cap_net_bind_service+ep
    state: present
- name: CoreDNS | Copy systemd unit file
  copy:
    src: coredns.service
    dest: /etc/systemd/system/coredns.service
    mode: 0644
  notify: CoreDNS | Restart service
- name: CoreDNS | Copy config files
  template:
    src: Corefile.j2
    dest: /etc/coredns/Corefile
    owner: coredns
    group: users
  notify: CoreDNS | Restart service
- name: CoreDNS | Copy zone files
  copy:
    src: zones/
    dest: /etc/coredns/zones
  notify: CoreDNS | Restart service
