prometheus_version: v2.2.1
scrape_jobs:
  - name: node_stats
    targets:
      - satellite.srv.qiu.home:9100
      - monarch.srv.qiu.home:9100
      - dns1.qiu.home:9100
      - dns2.qiu.home:9100
      - opi.srv.qiu.home:9100
    labels: []
  - name: coredns
    targets:
      - dns1.qiu.home:9153
      - dns2.qiu.home:9153
    labels: []
