---
- name: Traefik | Copy configuration
  template:
    src: traefik.toml.j2
    dest: /etc/traefik.toml
- name: Traefik | Run in container
  docker_container:
    name: traefik
    image: traefik:{{ traefik_version }}
    volumes:
      - "/etc/traefik.toml:/etc/traefik/traefik.toml"
    state: started
    restart_policy: always
    recreate: yes
    published_ports:
      - "80:80"
      - "8080:8080"
    log_driver: journald
