---
- name: Pihole | Sync local names
  copy:
    src: local.list
    dest: /etc/pihole/local.list
    mode: 0644
  become: yes
  notify: Pihole | Restart dnsmasq
- name: Pihole | Configure dnsmasq
  copy:
    src: dnsmasq.conf
    dest: /etc/dnsmasq.conf
    mode: 0644
  notify: Pihole | Restart dnsmasq
  become: yes
